### ISSUE TITLE
Configurable jump distance for forward/backward action

### ISSUE THREAD

**Issue by dzikoysk** [HarshPanchal18/Jumping-Lines#1]
It'd be nice, if users could adjust distance to jump. Sadly, at this moment it's not possible, because these values are hardcoded:

* https://github.com/HarshPanchal18/Jumping-Lines/blob/cbd08532ef0a6227a08371b4e430e66a96217011/src/main/kotlin/com/harsh/jumpinglines/JumpForwardLines.kt#L27
* https://github.com/HarshPanchal18/Jumping-Lines/blob/cbd08532ef0a6227a08371b4e430e66a96217011/src/main/kotlin/com/harsh/jumpinglines/JumpBackwardLines.kt#L23

As an example, I'd personally prefer to set them both to e.g. `5` :)

**Comment by HarshPanchal18** [comment]
I was thinking of this to let user set the lines to jump.
Thank you for your valuable feedback. Will start working on this. 👍🏼

**Comment by HarshPanchal18** [comment]
The functionality you suggested has been applied to the newer version of plugin. Kindly update it when it comes out of moderation. 👍🏼

**Comment by dzikoysk** [comment]
Thanks, I've updated the plugin and it works properly :))

**Comment by HarshPanchal18** [comment]
@dzikoysk Enjoy it and please make sure you rate and write review about plugin! It would be much appreciated :-)
