### ISSUE TITLE
Jumping Lines with Selection

### ISSUE THREAD

**Issue by Caffadras** [HarshPanchal18/Jumping-Lines#2]
**Is your feature request related to a problem? Please describe.**
First of all, it's an amazing plugin. I was surprised there is no such built-in functionality. 
I did configure a hotkey to be ctrl + up/down arrow. And as a logical follow-up, I tried to use this combination with shift, to both jump the cursor and select the code. But even after removing other intelij hotkeys, nothing happened. Moreover, I guess we can call it a little bug: if you make a selection and then jump lines, this will happen: 
![image](https://github.com/HarshPanchal18/Jumping-Lines/assets/88422510/8cc2e797-7eb4-4102-a4c2-15f30da065ec)
Notice that the cursor and the selection have diverged.

**Describe the solution you'd like**
I propose adding a functionality to select the code while jumping lines. I guess a separate hotkey should be added for this. So you will be able to select multiple lines at once.

**Comment by HarshPanchal18** [comment]
Glad you enjoyed a good time with plugin. I also noticed that same behavior a while ago.
Thank you for the valuable feedback. Will start working upon this. 👍🏼

**Comment by HarshPanchal18** [comment]
Okay! I did something like this.

https://github.com/HarshPanchal18/Jumping-Lines/assets/63415584/6eec8224-c09b-4afe-b484-67a6bcac4b34

If there is a selections inside current line, then the selection block will follow the cursor. Otherwise normal jumping will be performed.

**Comment by Caffadras** [comment]
Nice! I appreciate that you listen to user requests and try to implement them. Thank you. 

I just want to clarify a little more about the bug and my proposed feature, so we are on the same page. 
1. The bug when the selection and the cursor diverge. 
- Preconditions: 
Make a normal selection with either a default hotkey (shift+arrows) or the mouse. after that, perform a jumping line action. 
- Expected result: 
the selection should drop and the cursor should jump to the line.  the selection is expected to be dropped as it is the default behavior in any text redactor (in fact, in any OS).
- Actual result: 
the selection remains at the same line but the cursor jumps. 
- Your proposed solution:
As far as I have understood from your video, you addressed the bug in the following way: 
If there is already a selection while you make a jump line action, the selection will be extended to the cursor. Otherwise, no changes in the behavior.  
If yes, then I believe it is not quite intuitive, because such behavior differs from the default behavior. That's why I propose the result I described in  'expected result' section

2. Feature to make selection while jumping lines
To implement the desired behavior with selection I believe we should add 2 new hotkeys. One for jumping up + selection, and one for jumping down + selection. Such an approach will ensure that the selection will be easy to make (only one action is needed, pressing the hotkey), and at the same time, we allow users to change the hotkey to meet their preferences. 
So, the desired behavior will be: 
The user presses the new select + jump lines hotkey => the cursor will jump and the selection will follow it. 
Right after it, if the user jumps without the selection hotkey, the selection should drop.
So it should be exactly like the default behavior with shift+arrow hotkey. the only difference is the number of lines selected.  

Note that my proposed feature is separate from the bug (in the sense that it is not a solution to the bug, rather than a different request). I just combined both the bug and the feature in a single issue. 

I hope that you understand what I mean.
Once again, thanks for taking the time to make this plugin!

**Comment by HarshPanchal18** [comment]
Fine.
As I think, instead of allocating separate hotkeys for `jumping + selection`, I would rather give a checkbox on settings panel to know if the user wants to extend with selection or to extend after dropping out the selection.
Giving the developer(user) additional key combinations may lead to more crucial experience as he/she have to remember another couple of combinations.
I'm good to go with the both options. Let me know what's your views on this?

**Comment by Caffadras** [comment]
> I would rather give a checkbox on settings panel to know if the user wants to extend with selection or to extend after dropping out the selection.

Could you please elaborate a little bit on what the options for the checkbox mean? 

Does this mean that if the user selects the option `to extend with selection` and performs the next actions: 
1. make a standard selection of a piece of code (either with standard shift+arrow or with the mouse)
2. jump the lines 
The selection will be extended? 

But if he selects `to extend after dropping out the selection` and performs the same actions then the selection will be dropped on step 2 (jump the lines )?  

---

 
> Giving the developer(user) additional key combinations may lead to more crucial experience as he/she have to remember another couple of combinations.

I think we can make an argument that the more hotkeys the user can configure the better and the more customizable the tool is. Even Intellij - gives us the possibility to change every shortcut for every action, which is why it is so good and many developers love it. 
In our case, if the user does not want to have jump + select hotkeys, he can simply remove them in the IntelliJ keymap settings. Thus, I don't see any cons of adding new shortcuts, only pros. Please correct me If I am wrong. 


Also, I noticed now something in the video you have provided, and have a question: 
Once again, suppose the user makes a selection and jumps the line. At this point, some lines of code are selected. And now the user wants to extend his selection to the side. Let's say to the right, to capture the whole line. And he will use default shortcut for that (shift + right, or shift +ctrl + right, or shift + end, doesn't really matter)
My question is: will the selection behave as expected and expand to the right?

**Comment by HarshPanchal18** [comment]
> Also, I noticed now something in the video you have provided, and have a question:
Once again, suppose the user makes a selection and jumps the line. At this point, some lines of code are selected. And now the user wants to extend his selection to the side. Let's say to the right, to capture the whole line. And he will use default shortcut for that (shift + right, or shift +ctrl + right, or shift + end, doesn't really matter)
My question is: will the selection behave as expected and expand to the right?

Yes. The selection will behave as expected!

> In our case, if the user does not want to have jump + select hotkeys, he can simply remove them in the IntelliJ keymap settings. Thus, I don't see any cons of adding new shortcuts, only pros. Please correct me If I am wrong.

Okay, here is what I implemented:

https://github.com/HarshPanchal18/Jumping-Lines/assets/63415584/a941551c-e956-4d56-ad74-9a75d3cded43

* I have assigned a new couple of hotkeys to jump with selection `(ALT+SHIFT+COMMA)` & `(ALT+SHIFT+PERIOD)`.
Let me know does it seems good and as expected or not.

**Comment by Caffadras** [comment]
Looking good!
exactly what I expected

**Comment by HarshPanchal18** [comment]
Done! Updating the latest release. Write feedback after updating the plugin.

**Comment by Caffadras** [comment]
Nice!
So I am already satisfied with the implementation, and if you won't have time to do anything else, I am ok with that : ) 
But If you are up to the challenge, here are 2 things that I consider to be a bug 

https://github.com/HarshPanchal18/Jumping-Lines/assets/88422510/a4dc5d12-21e8-4f86-ad28-fea424034246
If you think it is not worth fixing them right now, no problems : )

**Comment by HarshPanchal18** [comment]
Don't worry. I already fixed it and the update will be reflected in a day or couple of day.
In the latest release, you don't need to start with selecting manually. The bug you are facing is also resolved. 😊

**Comment by Caffadras** [comment]
Thanks a lot❤️ 
Left a review : )

**Comment by HarshPanchal18** [comment]
My pleasure! Make sure you utilize it the most ;)
Don't forget to share it forward.
