### ISSUE TITLE
New Shift+J+K shortcut collides with Shift+J

### ISSUE THREAD

**Issue by dzikoysk** [HarshPanchal18/Jumping-Lines#3]
Hey, the newly added shortcut makes a collision with Shift+J, so we can't write uppercase `J` letter anymore 😅

**Comment by HarshPanchal18** [comment]
I also noticed the same but JetBrains provides a facility to remap the combination as per your preference. 😃
Or let me know which combination would suit better? 🤔

**Comment by dzikoysk** [comment]
So I personally removed this bind on my side, because I don't think I'll use this - I'm only using up/down jumps, for any other jumps I'm just using AceJump since it's a bit more universal for more detailed navigation. Not an issue for me, but just wanted to report that this might be not the best default value :)

**Comment by HarshPanchal18** [comment]
Great! I will fix it later with future version.
Thanks for your feedback! Make sure you utilize the plugin most ;-)

**Comment by HarshPanchal18** [comment]
> Hey, the newly added shortcut makes a collision with Shift+J, so we can't write uppercase `J` letter anymore 😅

@dzikoysk The conflict is being resolved and the update is live now. Make sure you update to the latest version.
